services:
  - type: web
    runtime: static
    name: party-word-guess
    buildCommand: echo "static-site"
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
